baseURL = "https://ksvblog.site/"
enableEmoji = true
enableInlineShortcodes = true
hasCJKLanguage = true
languageCode = 'my'
paginate = 6
summarylength = 10
title = "K's V/Blog"
# timeout = 20

canonifyURLs = true
disqusShortName = "heinhtetkyaw"
enableRobotsTXT = true
googleAnalytics = "UA-138756551-3"

pygmentsCodefences = true
pygmentsUseClasses = true
[params]
copyrightYearToken = "<YYYY>"
cyear = '© 2012'
mathJaxInitialize = "{ \"chtml\": { \"displayAlign\": \"left\" } }"
[params.social]
facebook = "CallMeHeinHtetKyaw" 
facebook_admin = "100008954538831" # This needs to be a page admin to get domain insights
github = "h2kyaw" 
instagram = "__heinhtetkyaw__" 
linkedin = "h2kyaw" 
pinterest = "h2kyaw" 
twitter = "HeinHtetKyaw_" 
twitter_domain = "https://ksvblog.site" # This domain shows in twitter cards as "View on `twitter_domain`"
youtube = "@heinhtetkyaw279" 

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[menu]
[[menu.main]]
Pre = 'fa-light fa-magnifying-glass'
Url = '/search'
name = 'Search'
pageRef = '/search'
weight = 5

[permalinks]
posts = "/post/:filename/"

[params.license]
copyrightFirstYear = 2012
name = "CC BY-NC-ND 4.0"
nameLong = "Attribution-NonCommercial-NoDerivatives 4.0 International"

[outputs]
home = ['html', 'rss', 'json']
page = ['html']
rss = ['rss']
section = ["HTML", "RSS"]
taxonomy = ['html', 'rss']
term = ['html', 'rss']

# [markup.highlight]
#     codeFences = true
#     guessSyntax = true
#     lineNoStart = 1
#     lineNos = true
#     lineNumbersInTable = false
#     tabWidth = 4
#     noClasses = false

[markup]
[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = true
hl_Lines = ''
hl_inline = false
lineAnchors = ''
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
noHl = false
style = 'average'
tabWidth = 4

[frontmatter]
date = ['date', 'publishdate', 'pubdate', 'published', 'lastmod', 'modified']
expiryDate = ['expirydate', 'unpublishdate']
lastmod = [':git', 'lastmod', 'modified', 'date', 'publishdate', 'pubdate', 'published']
publishDate = ['publishdate', 'pubdate', 'published', 'date']

[security]
[security.exec]
osEnv = ['(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|GO\w+|(XDG_CONFIG_)?HOME|USERPROFILE|SSH_AUTH_SOCK|DISPLAY|LANG|NPM_)$']
