[build]
command = "hugo --gc --minify"
publish = "public"

[build.environment]
HUGO_VERSION = "0.118.2"

[context.production.environment]
HUGO_ENABLEGITINFO = "true"
HUGO_ENV = "production"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
from = "/npmjs/*"
status = 200
to = "/npmjs/"

# If skip_processing = true, all other settings are ignored
[build.processing]
skip_processing = true
[build.processing.css]
bundle = true
minify = true
[build.processing.js]
bundle = true
minify = true
[build.processing.images]
compress = true

[[headers]]
for = "/css/*"
[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "/js/*"
[headers.values]

Cache-Control = "public, max-age=31536000"
[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "<origin>"
Content-Security-Policy = "frame-ancestors 'none'"
Cross-Origin-Embedder-Policy = "require-corp; report-to='default'"
Cross-Origin-Embedder-Policy-Report-Only = "require-corp; report-to='default"
Cross-Origin-Opener-Policy = "same-origin-allow-popups; report-to='default'"
Cross-Origin-Resource-Policy = "cross-origin"
Permissions-Policy = "accelerometer=(), camera=(), fullscreen=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=(), interest-cohort=()"
Referrer-Policy = "no-referrer"
X-Content-Type-Options = "nosniff"
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
#  Multi-value headers are expressed with multi-line strings
cache-control = '''
	max-age=0,
	no-cache,
	no-store,
	must-revalidate'''
