/** @type {import('tailwindcss').Config} */
module.exports = {
  // purge: {
  //   enabled: process.env.HUGO_ENVIRONMENT === 'production',
  //   content: [
  //     './layouts/**/*.html',
  //     './content/**/*.md',
  //     './content/**/*.html',
  //   ],
  // },
  // purge: ['layouts/**/*.html', '../content/*.md',],
  content: ['content/*.md', 'content/**/*.md', 'layouts/**/*.html'],
  // purge: {
  //   enabled: process.env.HUGO_ENVIRONMENT === 'production',
  //   content: [
  //     './layouts/**/*.html',
  //     './content/**/*.md',
  //     './content/**/*.html',
  //   ],
  // },
  darkMode: 'class',
  // content: [],
  theme: {
    extend: {
      colors: {
        transparent: 'transparent',
        current: 'currentColor',
        white: '#ffffff',
        purple: '#3f3cbb',
        midnight: '#121063',
        metal: '#565584',
        tahiti: '#3ab7bf',
        silver: '#ecebff',
        'bubble-gum': '#ff77e9',
        bermuda: '#78dcca',
        h: 'rgb(255, 64, 136)',
        u: 'rgb(5, 148, 203)',
        g: 'rgb(51, 186, 145)',
        o: 'rgb(235, 185, 81)',
        primary: {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
          950: '#172554',
        },
      },
    },
    fontFamily: {
      body: [
        'Miriam Libre',
        'Fira San',
        'Inter',
        'ui-sans-serif',
        'system-ui',
        '-apple-system',
        'system-ui',
        'Segoe UI',
        'Roboto',
        'Helvetica Neue',
        'Arial',
        'Noto Sans',
        'sans-serif',
        'Apple Color Emoji',
        'Segoe UI Emoji',
        'Segoe UI Symbol',
        'Noto Color Emoji',
      ],
      sans: [
        'Miriam Libre',
        'Fira San',
        'Inter',
        'ui-sans-serif',
        'system-ui',
        '-apple-system',
        'system-ui',
        'Segoe UI',
        'Roboto',
        'Helvetica Neue',
        'Arial',
        'Noto Sans',
        'sans-serif',
        'Apple Color Emoji',
        'Segoe UI Emoji',
        'Segoe UI Symbol',
        'Noto Color Emoji',
      ],
    },
    screens: {
      sm: '480px',
      md: '768px',
      lg: '1100px',
      xl: '1440px',
    },
  },
};
